server:
  port: 8080

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
    show-sql: true

  # oauth2 ? ???? ???? ??? TODO ? ???? ?
  security:
    oauth2:
      client:
        registration:
          # /oauth2/authorization/google
          google:
            client-id: google_client_id # TODO https://console.cloud.google.com
            client-secret: google_client_secret # TODO
            scope: profile,email
          # ???? Spring Security? ?? ???? ?? ??? CommonOAuth2Provider ?? ??? ??? ???? ????.
          # /oauth2/authorization/naver
          naver:
            client-id: naver_client_id # TODO https://developers.naver.com/apps/#/register?api=nvlogin
            client-secret: naver_client_secret # TODO
            redirect_uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
          # /oauth2/authorization/kakao
          kakao:
            client-id: kakao_client_id # TODO https://developers.kakao.com/product/kakaoLogin
            client-secret: kakao_client_secret # TODO
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            # ??? ?? user_name ? ??? ?????? response? ??????. (??? ?? ??? ???? JSON ?? ????)
            # response? user_name?? ???? ?? ?? ??? response? id? user_name?? ????. (??? ?????? ?? ??? ??? ? ?? ??)
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info
  health:
    mail:
      enabled: false
